---
title: "ABX"
output: html_document
---

```{r}
library(plyr)
library(ggplot2)
```


```{r warning = FALSE}
# Files utilisés
variable_results <- readr::read_delim("./distances/okay/by_vowel_okay.csv", " ")
variable_distances <- readr::read_delim("./distances/okay/distances_okay.txt", " ")
fixed_results <- readr::read_delim("./fixed_length/qu1_v/data_fixed.csv", ";")
fixed_distances <- readr::read_delim("./fixed_length/qu1_v/data_fixed.txt", " ")
item <- readr::read_delim("./fixed_length/qu1_v/data_fixed.item", " ")
item_v <- readr::read_delim("./distances/okay/data_okay.item", " ")

# Change column names because why not
names(fixed_distances)[which(names(fixed_distances)=="d(A, B)")] <- "dist"
names(variable_distances)[which(names(variable_distances)=="d(A, B)")] <- "dist"

# Pour les fixed-width results
item_f_B <- dplyr::select(fixed_distances, dplyr::ends_with("_B"))
item_f_B_ <- dplyr::inner_join(item_f_B, item, by=c(file_B="#file", onset_B="onset", offset_B="offset"))
item_f_B__ <- dplyr::rename_at(item_f_B_, names(item_f_B_)[!endsWith(names(item_f_B_), "_B")], function(x) paste0(x, "_B"))

item_f_A <- dplyr::select(fixed_distances, dplyr::ends_with("_A"))
item_f_A_ <- dplyr::inner_join(item_f_A, item, by=c(file_A="#file", onset_A="onset", offset_A="offset"))
item_f_A__ <- dplyr::rename_at(item_f_A_, names(item_f_A_)[!endsWith(names(item_f_A_), "_A")], function(x) paste0(x, "_A"))

# Prepare les colonnes qui m interessent dans A et B
item_f_B_clean <- item_f_B__
item_f_B_clean$pulm_B <- NULL
item_f_B_clean$place_B <- NULL
item_f_B_clean$vowel_B <- NULL
item_f_B_clean$position_B <- NULL
item_f_B_clean$new_B <- NULL
colnames(item_f_B_clean)[colnames(item_f_B_clean)=="speaker_B"] <- "speaker"
colnames(item_f_B_clean)[colnames(item_f_B_clean)=="question_B"] <- "question"

item_f_A_clean <- item_f_A__
item_f_A_clean$pulm_A <- NULL
item_f_A_clean$place_A <- NULL
item_f_A_clean$vowel_A <- NULL
item_f_A_clean$position_A <- NULL
item_f_A_clean$speaker_A <- NULL
item_f_A_clean$question_A <- NULL
item_f_A_clean$new_A <- NULL

# Selectionne le distance score
distance_f_score <- dplyr::select(fixed_distances, dplyr::starts_with("d"))

# Met tout dans un meme tibble
distances_f_better <- dplyr::bind_cols(item_f_A_clean, item_f_B_clean, distance_f_score)
distances_f_better$onset_A <- NULL
distances_f_better$offset_A <- NULL
distances_f_better$onset_B <- NULL
distances_f_better$offset_B <- NULL
names(distances_f_better)[which(names(distances_f_better)=="dist")] <- "dist_fixed"
# Create a new table with fewer information                   
names(distances_f_better)[which(names(distances_f_better)=="#item_A")] <- "item_A"
names(distances_f_better)[which(names(distances_f_better)=="#item_B")] <- "item_B"

####################
# Pour les variable-width results
item_v_B <- dplyr::select(variable_distances, dplyr::ends_with("_B"))
item_v_B_ <- dplyr::inner_join(item_v_B, item_v, by=c(file_B="#file", onset_B="onset", offset_B="offset"))
item_v_B__ <- dplyr::rename_at(item_v_B_, names(item_v_B_)[!endsWith(names(item_v_B_), "_B")], function(x) paste0(x, "_B"))

item_v_A <- dplyr::select(variable_distances, dplyr::ends_with("_A"))
item_v_A_ <- dplyr::inner_join(item_v_A, item_v, by=c(file_A="#file", onset_A="onset", offset_A="offset"))
item_v_A__ <- dplyr::rename_at(item_v_A_, names(item_v_A_)[!endsWith(names(item_v_A_), "_A")], function(x) paste0(x, "_A"))

# Prepare les colonnes qui m interessent dans A et B
item_v_B_clean <- item_v_B__
item_v_B_clean$pulm_B <- NULL
item_v_B_clean$place_B <- NULL
item_v_B_clean$vowel_B <- NULL
item_v_B_clean$position_B <- NULL
item_v_B_clean$new_B <- NULL
colnames(item_v_B_clean)[colnames(item_v_B_clean)=="speaker_B"] <- "speaker"
colnames(item_v_B_clean)[colnames(item_v_B_clean)=="question_B"] <- "question"

item_v_A_clean <- item_v_A__
item_v_A_clean$pulm_A <- NULL
item_v_A_clean$place_A <- NULL
item_v_A_clean$vowel_A <- NULL
item_v_A_clean$position_A <- NULL
item_v_A_clean$speaker_A <- NULL
item_v_A_clean$question_A <- NULL
item_v_A_clean$new_A <- NULL

# Selectionne le distance score
distance_v_score <- dplyr::select(variable_distances, dplyr::starts_with("d"))

# Met tout dans un meme tibble
distances_v_better <- dplyr::bind_cols(item_v_A_clean, item_v_B_clean, distance_v_score)
distances_v_better$onset_A <- NULL
distances_v_better$offset_A <- NULL
distances_v_better$onset_B <- NULL
distances_v_better$offset_B <- NULL
names(distances_v_better)[which(names(distances_v_better)=="dist")] <- "dist_variable"
# Create a new table with fewer information                   
names(distances_v_better)[which(names(distances_v_better)=="#item_A")] <- "item_A"
names(distances_v_better)[which(names(distances_v_better)=="#item_B")] <- "item_B"

#################
distances_even_better <- dplyr::inner_join(distances_f_better, distances_v_better, by=c(item_A="item_A", item_B="item_B", file_A="file_A", file_B="file_B", phone_A="phone_A", phone_B="phone_B", speaker="speaker", question="question"))
distances_even_better$onset_A <- NULL
distances_even_better$offset_A <- NULL
distances_even_better$onset_B <- NULL
distances_even_better$offset_B <- NULL
```